LABEL_TRUE = 'T'
LABEL_FALSE = 'F'
LABEL_OTHER = 'X'
ALLOWED_LABELS = (LABEL_TRUE, LABEL_FALSE, LABEL_OTHER)
PRIVATE_KEY_CATEGORY = "PEM Private Key"
MULTI_PATTERN_RULES = ("AWS Multi", "Google Multi", "JWK")
